### ISSUE TITLE
Small typo in manual

### ISSUE THREAD

**Issue by romainreignier** [OLIMEX/USB-4SERIAL#1]
Hi, nice product!

While browsing the manual, I have noticed a small typo on page 9.
In the center of the page, a `p` is missing in "RS485 Jumer".

It's nice to provide the ODT file for the manual, I could have opened a pull request, but you would not have been able to easily see the diff of my changes.
You might want to switch to the `.fodt` file format, which is a flat XML version of the ODT. The file is bigger because it's ASCII but it allows to review the changes in git.

**Comment by TsvetanUsunov** [comment]
thanks, fixed!
